# Generated by Django 4.2.1 on 2023-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Women'), ('W', 'Men'), ('MF', 'Muslim'), ('SW', 'School Wear'), ('B', 'Baby'), ('S', 'Sports')], max_length=2),
        ),
    ]
